#!/bin/sh
# file: screen-session
# author: Artur Skonecki
# website: http://adb.cba.pl
# description: screen-session.py script starter
# it is necessary to run screen-session.py embedded in other screen session to be able to run it from saved/loaded screen session

screen -X sessionname
rawargument=`screen -Q @lastmsg`

testargument=`screen -Q @tty`

screen-session.py --getopt $*
if [ $? -eq 0 ]; then
    if [ `echo ${testargument} | grep -c "^/dev"` -eq 1 ]; then
        echo "running inside patched Screen session"
        argument="--current-session "`echo $rawargument | python -c "import sys; print(sys.stdin.read().split('\'',1)[1].rsplit('\'',1)[0])"`
        #echo $argument $* | xargs screen-session.py $argument $*
        #screen -m -c /dev/null screen-session.py --wait $argument $*
        screen -m -c /dev/null screen-session.py $argument $*
    else
        echo "not running inside patched Screen, this session cannot be saved properly"
        argument=""
        screen-session.py $argument $*
    fi
else
    screen-session.py  $*
fi


